'use strict'

const nameCache = {}

module.exports.getTerserConfig = () => ({
  compress: {
    arrows: false,
    booleans_as_integers: false,
    booleans: true,
    collapse_vars: true,
    comparisons: true,
    computed_props: true,
    conditionals: true,
    dead_code: true,
    directives: true,
    drop_console: false,
    evaluate: true,
    hoist_funs: true,
    hoist_props: true,
    inline: true,
    join_vars: true,
    keep_classnames: false,
    keep_fnames: false,
    typeofs: true,
    loops: true,
    pure_getters: true,
    side_effects: true,
    switches: true,
    toplevel: true,
    unused: true,
    unsafe_math: true,
    unsafe_proto: true,
    properties: true,
    passes: 3,
  },
  mangle: {
    eval: true,
    keep_classnames: false,
    keep_fnames: false,
    module: true,
    safari10: false,
    toplevel: true,
  },
  output: {
    indent_level: 2,
    ascii_only: false,
    braces: false,
    comments: false,
    quote_keys: false,
    quote_style: 3,
    safari10: false,
    ecma: 5,
  },
  nameCache,
})
