name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  unit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 8

    - name: install root-deps
      run: |
        npm i
        npm i -g lerna

    - name: build
      run: npm run build

    - name: units
      run: npm run unit
      env:
        CI: true

  linters:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 8

    - name: install root-deps
      run: npm i --ignore-scripts

    - name: commitlint
      run: node ./scripts/commitlint.js

    - name: eslint
      run: npm run lint
